version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    volumes:
      # - h2_data:/opt/keycloak/data
      - ${PWD}/target/keycloak-account-v1-0.1.jar:/opt/keycloak/providers/keycloak-account-v1-0.1.jar
    environment:
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
